import { Component } from '@angular/core';
import { Router, RouterLink } from '@angular/router';
import { AsyncPipe, NgFor, NgIf } from '@angular/common';
import { Preferences } from '@capacitor/preferences';
import { addIcons } from 'ionicons';
import {
  homeOutline,
  personCircleOutline,
  logInOutline,
  logOutOutline,
  qrCodeOutline,
  chatbubblesOutline,
  calendarOutline,
  ribbonOutline,
} from 'ionicons/icons';
import {
  IonApp,
  IonRouterOutlet,
  IonMenu,
  IonMenuToggle,
  IonHeader,
  IonToolbar,
  IonTitle,
  IonContent,
  IonList,
  IonItem,
  IonIcon,
  IonLabel,
  IonSelect,
  IonSelectOption,
} from '@ionic/angular/standalone';

import { AuthService } from './services/auth.service';

@Component({
  selector: 'app-root',
  templateUrl: 'app.component.html',
  standalone: true,
  imports: [IonLabel, 
    IonApp,
    IonRouterOutlet,
    IonMenu,
    IonMenuToggle,
    IonHeader,
    IonToolbar,
    IonTitle,
    IonContent,
    IonList,
    IonItem,
    IonIcon,
    IonSelect,
    IonSelectOption,
    RouterLink,
    NgFor,
    NgIf,
    AsyncPipe,
  ],
})
export class AppComponent {
  // Observable utilisé dans le menu
  isAuthenticated$ = this.auth.isAuthenticated$;
  selectedLanguage: LanguageCode = 'en';

  readonly languages: { code: LanguageCode; label: string; flag: string }[] = [
    { code: 'en', label: 'English', flag: '🇬🇧' },
    { code: 'nl', label: 'Nederlands', flag: '🇳🇱' },
    { code: 'fr', label: 'Français', flag: '🇫🇷' },
    { code: 'de', label: 'Deutsch', flag: '🇩🇪' },
    { code: 'pl', label: 'Polski', flag: '🇵🇱' },
    { code: 'lt', label: 'Lietuvių', flag: '🇱🇹' },
    { code: 'es', label: 'Español', flag: '🇪🇸' },
  ];

  private readonly translations: Record<LanguageCode, Record<string, string>> = {
    en: {
      home: 'Home',
      account: 'My account',
      login: 'Log in',
      logout: 'Log out',
      vcard: 'vCard',
      chat: 'Chat',
      myEvents: 'My Events',
      calendar: 'Calendar',
      language: 'Language',
      default: 'Default',
      // Login page
      loginTitle: 'Log in',
      loginUsername: 'Username',
      loginPassword: 'Password',
      loginSubmit: 'Log in',
      loginError: 'Login failed',
      // Home page
      lifeBegins: 'LIFE BEGINS ...',
      comfortZone: '... at the end of your comfort zone',
      iNeedHelp: 'I NEED HELP',
      // Profile page
      profileTitle: 'My account',
      profileLoading: 'Loading profile…',
      profileRetry: 'Retry',
      profileFirstname: 'First name',
      profileLastname: 'Last name',
      profileEmail: 'Email',
      profileBirthday: 'Date of birth',
      profileUsername: 'Username',
      profileSave: 'Save',
      profileLogout: 'Log out',
      profileSaved: 'Profile updated ✅',
      profileLoadError: 'Failed to load profile',
      profileSaveError: 'Failed to update profile',
      // vCard page
      vcardTitle: 'My vCard',
      vcardYours: 'Your Kingsmen vCard',
      vcardGuest: 'Guest Mode',
      vcardNotLogged: 'You are not logged in. Demo QR Code displayed.',
      vcardGenerating: 'Generating QR Code…',
      vcardRetry: 'Retry',
      vcardRefresh: 'Refresh',
      vcardError: 'Unable to generate QR Code',
      // Chat page
      chatTitle: 'Chat',
      chatPlaceholder: 'Type a message…',
      chatReply: 'Reply',
      chatReplyTo: 'Reply to',
      chatUser: 'User',
      chatOpenEmoji: 'Open emojis',
      chatCloseEmoji: 'Close emojis',
      // My Events page
      eventTitle: 'My Events',
      eventLoading: 'Loading event information...',
      eventEmpty: 'No information available for this event yet.',
      eventNoEvent: 'You are not registered for any event.',
      eventOpenFile: 'Open file',
      eventTypePin: 'Pinned',
      eventTypeSong: 'Song',
      eventTypeFile: 'File',
      eventTypePoll: 'Poll',
      eventTypeInfo: 'Info',
      // Calendar page
      calTitle: 'Kingsmen calendar',
      calDate: 'Date',
      calTime: 'Time',
      calClose: 'Close',
      calWeekDays: 'Mon,Tue,Wed,Thu,Fri,Sat,Sun',
      calMonths: 'January,February,March,April,May,June,July,August,September,October,November,December',
    },
    nl: {
      home: 'Start',
      account: 'Mijn account',
      login: 'Inloggen',
      logout: 'Uitloggen',
      vcard: 'vCard',
      chat: 'Chat',
      myEvents: 'Mijn evenementen',
      calendar: 'Kalender',
      language: 'Taal',
      default: 'Standaard',
      // Login page
      loginTitle: 'Inloggen',
      loginUsername: 'Gebruikersnaam',
      loginPassword: 'Wachtwoord',
      loginSubmit: 'Inloggen',
      loginError: 'Inloggen mislukt',
      // Home page
      lifeBegins: 'HET LEVEN BEGINT ...',
      comfortZone: '... buiten je comfortzone',
      iNeedHelp: 'IK HEB HULP NODIG',
      // Profile page
      profileTitle: 'Mijn account',
      profileLoading: 'Profiel laden…',
      profileRetry: 'Opnieuw proberen',
      profileFirstname: 'Voornaam',
      profileLastname: 'Achternaam',
      profileEmail: 'E-mail',
      profileBirthday: 'Geboortedatum',
      profileUsername: 'Gebruikersnaam',
      profileSave: 'Opslaan',
      profileLogout: 'Uitloggen',
      profileSaved: 'Profiel bijgewerkt ✅',
      profileLoadError: 'Kan profiel niet laden',
      profileSaveError: 'Bijwerken mislukt',
      // vCard page
      vcardTitle: 'Mijn vCard',
      vcardYours: 'Jouw Kingsmen vCard',
      vcardGuest: 'Gastmodus',
      vcardNotLogged: 'Je bent niet ingelogd. Demo QR-code weergegeven.',
      vcardGenerating: 'QR-code genereren…',
      vcardRetry: 'Opnieuw proberen',
      vcardRefresh: 'Vernieuwen',
      vcardError: 'Kan QR-code niet genereren',
      // Chat page
      chatTitle: 'Chat',
      chatPlaceholder: 'Typ een bericht…',
      chatReply: 'Reageren',
      chatReplyTo: 'Reactie op',
      chatUser: 'Gebruiker',
      chatOpenEmoji: 'Emoji openen',
      chatCloseEmoji: 'Emoji sluiten',
      // My Events page
      eventTitle: 'Mijn evenementen',
      eventLoading: 'Evenementinformatie laden...',
      eventEmpty: 'Nog geen informatie beschikbaar voor dit evenement.',
      eventNoEvent: 'Je bent niet ingeschreven voor een evenement.',
      eventOpenFile: 'Bestand openen',
      eventTypePin: 'Vastgemaakt',
      eventTypeSong: 'Lied',
      eventTypeFile: 'Bestand',
      eventTypePoll: 'Peiling',
      eventTypeInfo: 'Info',
      // Calendar page
      calTitle: 'Kingsmen kalender',
      calDate: 'Datum',
      calTime: 'Tijd',
      calClose: 'Sluiten',
      calWeekDays: 'Ma,Di,Wo,Do,Vr,Za,Zo',
      calMonths: 'Januari,Februari,Maart,April,Mei,Juni,Juli,Augustus,September,Oktober,November,December',
    },
    fr: {
      home: 'Accueil',
      account: 'Mon compte',
      login: 'Se connecter',
      logout: 'Se déconnecter',
      vcard: 'vCard',
      chat: 'Chat',
      myEvents: 'Mes événements',
      calendar: 'Calendrier',
      language: 'Langue',
      default: 'Par défaut',
      // Login page
      loginTitle: 'Se connecter',
      loginUsername: "Nom d'utilisateur",
      loginPassword: 'Mot de passe',
      loginSubmit: 'Se connecter',
      loginError: 'Échec de la connexion',
      // Home page
      lifeBegins: 'LA VIE COMMENCE ...',
      comfortZone: '... à la fin de ta zone de confort',
      iNeedHelp: "J'AI BESOIN D'AIDE",
      // Profile page
      profileTitle: 'Mon compte',
      profileLoading: 'Chargement du profil…',
      profileRetry: 'Réessayer',
      profileFirstname: 'Prénom',
      profileLastname: 'Nom',
      profileEmail: 'Email',
      profileBirthday: 'Date de naissance',
      profileUsername: "Nom d'utilisateur",
      profileSave: 'Enregistrer',
      profileLogout: 'Déconnexion',
      profileSaved: 'Profil mis à jour ✅',
      profileLoadError: 'Impossible de charger le profil',
      profileSaveError: 'Échec de la mise à jour',
      // vCard page
      vcardTitle: 'Ma vCard',
      vcardYours: 'Votre vCard Kingsmen',
      vcardGuest: 'Mode invité',
      vcardNotLogged: 'Vous n\'êtes pas connecté. QR Code de démonstration affiché.',
      vcardGenerating: 'Génération du QR Code…',
      vcardRetry: 'Réessayer',
      vcardRefresh: 'Actualiser',
      vcardError: 'Impossible de générer le QR Code',
      // Chat page
      chatTitle: 'Chat',
      chatPlaceholder: 'Tapez un message…',
      chatReply: 'Répondre',
      chatReplyTo: 'Réponse à',
      chatUser: 'Utilisateur',
      chatOpenEmoji: 'Ouvrir les emojis',
      chatCloseEmoji: 'Fermer les emojis',
      // My Events page
      eventTitle: 'Mes événements',
      eventLoading: 'Chargement des informations...',
      eventEmpty: 'Aucune information disponible pour cet événement.',
      eventNoEvent: 'Vous n\'êtes inscrit à aucun événement.',
      eventOpenFile: 'Ouvrir le fichier',
      eventTypePin: 'Épinglé',
      eventTypeSong: 'Chanson',
      eventTypeFile: 'Fichier',
      eventTypePoll: 'Sondage',
      eventTypeInfo: 'Info',
      // Calendar page
      calTitle: 'Calendrier Kingsmen',
      calDate: 'Date',
      calTime: 'Heure',
      calClose: 'Fermer',
      calWeekDays: 'Lun,Mar,Mer,Jeu,Ven,Sam,Dim',
      calMonths: 'Janvier,Février,Mars,Avril,Mai,Juin,Juillet,Août,Septembre,Octobre,Novembre,Décembre',
    },
    de: {
      home: 'Startseite',
      account: 'Mein Konto',
      login: 'Anmelden',
      logout: 'Abmelden',
      vcard: 'vCard',
      chat: 'Chat',
      myEvents: 'Meine Events',
      calendar: 'Kalender',
      language: 'Sprache',
      default: 'Standard',
      // Login page
      loginTitle: 'Anmelden',
      loginUsername: 'Benutzername',
      loginPassword: 'Passwort',
      loginSubmit: 'Anmelden',
      loginError: 'Anmeldung fehlgeschlagen',
      // Home page
      lifeBegins: 'DAS LEBEN BEGINNT ...',
      comfortZone: '... am Ende deiner Komfortzone',
      iNeedHelp: 'ICH BRAUCHE HILFE',
      // Profile page
      profileTitle: 'Mein Konto',
      profileLoading: 'Profil wird geladen…',
      profileRetry: 'Erneut versuchen',
      profileFirstname: 'Vorname',
      profileLastname: 'Nachname',
      profileEmail: 'E-Mail',
      profileBirthday: 'Geburtsdatum',
      profileUsername: 'Benutzername',
      profileSave: 'Speichern',
      profileLogout: 'Abmelden',
      profileSaved: 'Profil aktualisiert ✅',
      profileLoadError: 'Profil konnte nicht geladen werden',
      profileSaveError: 'Aktualisierung fehlgeschlagen',
      // vCard page
      vcardTitle: 'Meine vCard',
      vcardYours: 'Deine Kingsmen vCard',
      vcardGuest: 'Gastmodus',
      vcardNotLogged: 'Du bist nicht angemeldet. Demo-QR-Code wird angezeigt.',
      vcardGenerating: 'QR-Code wird erstellt…',
      vcardRetry: 'Erneut versuchen',
      vcardRefresh: 'Aktualisieren',
      vcardError: 'QR-Code konnte nicht erstellt werden',
      // Chat page
      chatTitle: 'Chat',
      chatPlaceholder: 'Nachricht schreiben…',
      chatReply: 'Antworten',
      chatReplyTo: 'Antwort an',
      chatUser: 'Benutzer',
      chatOpenEmoji: 'Emojis öffnen',
      chatCloseEmoji: 'Emojis schließen',
      // My Events page
      eventTitle: 'Meine Events',
      eventLoading: 'Eventinformationen werden geladen...',
      eventEmpty: 'Noch keine Informationen für dieses Event verfügbar.',
      eventNoEvent: 'Du bist für kein Event angemeldet.',
      eventOpenFile: 'Datei öffnen',
      eventTypePin: 'Angeheftet',
      eventTypeSong: 'Lied',
      eventTypeFile: 'Datei',
      eventTypePoll: 'Umfrage',
      eventTypeInfo: 'Info',
      // Calendar page
      calTitle: 'Kingsmen Kalender',
      calDate: 'Datum',
      calTime: 'Uhrzeit',
      calClose: 'Schließen',
      calWeekDays: 'Mo,Di,Mi,Do,Fr,Sa,So',
      calMonths: 'Januar,Februar,März,April,Mai,Juni,Juli,August,September,Oktober,November,Dezember',
    },
    pl: {
      home: 'Strona glowna',
      account: 'Moje konto',
      login: 'Zaloguj sie',
      logout: 'Wyloguj sie',
      vcard: 'vCard',
      chat: 'Czat',
      myEvents: 'Moje wydarzenia',
      calendar: 'Kalendarz',
      language: 'Jezyk',
      default: 'Domyslny',
      // Login page
      loginTitle: 'Zaloguj sie',
      loginUsername: 'Nazwa uzytkownika',
      loginPassword: 'Haslo',
      loginSubmit: 'Zaloguj sie',
      loginError: 'Logowanie nie powiodlo sie',
      // Home page
      lifeBegins: 'ZYCIE ZACZYNA SIE ...',
      comfortZone: '... poza strefa komfortu',
      iNeedHelp: 'POTRZEBUJE POMOCY',
      // Profile page
      profileTitle: 'Moje konto',
      profileLoading: 'Ladowanie profilu…',
      profileRetry: 'Sprobuj ponownie',
      profileFirstname: 'Imie',
      profileLastname: 'Nazwisko',
      profileEmail: 'E-mail',
      profileBirthday: 'Data urodzenia',
      profileUsername: 'Nazwa uzytkownika',
      profileSave: 'Zapisz',
      profileLogout: 'Wyloguj sie',
      profileSaved: 'Profil zaktualizowany ✅',
      profileLoadError: 'Nie mozna zaladowac profilu',
      profileSaveError: 'Aktualizacja nie powiodla sie',
      // vCard page
      vcardTitle: 'Moja vCard',
      vcardYours: 'Twoja vCard Kingsmen',
      vcardGuest: 'Tryb goscia',
      vcardNotLogged: 'Nie jestes zalogowany. Wyswietlany jest demonstracyjny kod QR.',
      vcardGenerating: 'Generowanie kodu QR…',
      vcardRetry: 'Sprobuj ponownie',
      vcardRefresh: 'Odswiez',
      vcardError: 'Nie mozna wygenerowac kodu QR',
      // Chat page
      chatTitle: 'Czat',
      chatPlaceholder: 'Napisz wiadomosc…',
      chatReply: 'Odpowiedz',
      chatReplyTo: 'Odpowiedz do',
      chatUser: 'Uzytkownik',
      chatOpenEmoji: 'Otworz emoji',
      chatCloseEmoji: 'Zamknij emoji',
      // My Events page
      eventTitle: 'Moje wydarzenia',
      eventLoading: 'Ladowanie informacji o wydarzeniu...',
      eventEmpty: 'Brak informacji dla tego wydarzenia.',
      eventNoEvent: 'Nie jestes zapisany na zadne wydarzenie.',
      eventOpenFile: 'Otworz plik',
      eventTypePin: 'Przypiety',
      eventTypeSong: 'Piosenka',
      eventTypeFile: 'Plik',
      eventTypePoll: 'Ankieta',
      eventTypeInfo: 'Info',
      // Calendar page
      calTitle: 'Kalendarz Kingsmen',
      calDate: 'Data',
      calTime: 'Godzina',
      calClose: 'Zamknij',
      calWeekDays: 'Pon,Wt,Śr,Czw,Pt,Sob,Niedz',
      calMonths: 'Styczeń,Luty,Marzec,Kwiecień,Maj,Czerwiec,Lipiec,Sierpień,Wrzesień,Październik,Listopad,Grudzień',
    },
    lt: {
      home: 'Pagrindinis',
      account: 'Mano paskyra',
      login: 'Prisijungti',
      logout: 'Atsijungti',
      vcard: 'vCard',
      chat: 'Pokalbiai',
      myEvents: 'Mano renginiai',
      calendar: 'Kalendorius',
      language: 'Kalba',
      default: 'Numatytoji',
      // Login page
      loginTitle: 'Prisijungti',
      loginUsername: 'Naudotojo vardas',
      loginPassword: 'Slaptazodis',
      loginSubmit: 'Prisijungti',
      loginError: 'Prisijungti nepavyko',
      // Home page
      lifeBegins: 'GYVENIMAS PRASIDEDA ...',
      comfortZone: '... komforto zonos pabaigoje',
      iNeedHelp: 'MAN REIKIA PAGALBOS',
      // Profile page
      profileTitle: 'Mano paskyra',
      profileLoading: 'Profilis kraunamas…',
      profileRetry: 'Bandyti dar karta',
      profileFirstname: 'Vardas',
      profileLastname: 'Pavarde',
      profileEmail: 'El. pastas',
      profileBirthday: 'Gimimo data',
      profileUsername: 'Naudotojo vardas',
      profileSave: 'Issaugoti',
      profileLogout: 'Atsijungti',
      profileSaved: 'Profilis atnaujintas ✅',
      profileLoadError: 'Nepavyko ikelti profilio',
      profileSaveError: 'Nepavyko atnaujinti',
      // vCard page
      vcardTitle: 'Mano vCard',
      vcardYours: 'Jūsų Kingsmen vCard',
      vcardGuest: 'Svečio režimas',
      vcardNotLogged: 'Nesate prisijunge. Rodomas demonstracinis QR kodas.',
      vcardGenerating: 'Generuojamas QR kodas…',
      vcardRetry: 'Bandyti dar karta',
      vcardRefresh: 'Atnaujinti',
      vcardError: 'Nepavyko sugeneruoti QR kodo',
      // Chat page
      chatTitle: 'Pokalbiai',
      chatPlaceholder: 'Parasykite zinute…',
      chatReply: 'Atsakyti',
      chatReplyTo: 'Atsakymas i',
      chatUser: 'Vartotojas',
      chatOpenEmoji: 'Atidaryti emoji',
      chatCloseEmoji: 'Uzdaryti emoji',
      // My Events page
      eventTitle: 'Mano renginiai',
      eventLoading: 'Kraunama renginio informacija...',
      eventEmpty: 'Kol kas nėra informacijos apie šį renginį.',
      eventNoEvent: 'Jūs nesate užsiregistravęs į jokią renginį.',
      eventOpenFile: 'Atidaryti failą',
      eventTypePin: 'Prisegta',
      eventTypeSong: 'Daina',
      eventTypeFile: 'Failas',
      eventTypePoll: 'Apklausa',
      eventTypeInfo: 'Info',
      // Calendar page
      calTitle: 'Kingsmen kalendorius',
      calDate: 'Data',
      calTime: 'Laikas',
      calClose: 'Uždaryti',
      calWeekDays: 'Pr,An,Tr,Kt,Pn,Št,Sk',
      calMonths: 'Sausis,Vasaris,Kovas,Balandis,Gegužė,Birželis,Liepa,Rugpjūtis,Rugsėjis,Spalis,Lapkritis,Gruodis',
    },
    es: {
      home: 'Inicio',
      account: 'Mi cuenta',
      login: 'Iniciar sesion',
      logout: 'Cerrar sesion',
      vcard: 'vCard',
      chat: 'Chat',
      myEvents: 'Mis eventos',
      calendar: 'Calendario',
      language: 'Idioma',
      default: 'Predeterminado',
      // Login page
      loginTitle: 'Iniciar sesion',
      loginUsername: 'Usuario',
      loginPassword: 'Contrasena',
      loginSubmit: 'Iniciar sesion',
      loginError: 'Error al iniciar sesion',
      // Home page
      lifeBegins: 'LA VIDA EMPIEZA ...',
      comfortZone: '... al final de tu zona de confort',
      iNeedHelp: 'NECESITO AYUDA',
      // Profile page
      profileTitle: 'Mi cuenta',
      profileLoading: 'Cargando perfil…',
      profileRetry: 'Reintentar',
      profileFirstname: 'Nombre',
      profileLastname: 'Apellido',
      profileEmail: 'Correo',
      profileBirthday: 'Fecha de nacimiento',
      profileUsername: 'Usuario',
      profileSave: 'Guardar',
      profileLogout: 'Cerrar sesion',
      profileSaved: 'Perfil actualizado ✅',
      profileLoadError: 'No se pudo cargar el perfil',
      profileSaveError: 'Error al actualizar',
      // vCard page
      vcardTitle: 'Mi vCard',
      vcardYours: 'Tu vCard Kingsmen',
      vcardGuest: 'Modo invitado',
      vcardNotLogged: 'No has iniciado sesion. Se muestra un QR de demostración.',
      vcardGenerating: 'Generando código QR…',
      vcardRetry: 'Reintentar',
      vcardRefresh: 'Actualizar',
      vcardError: 'No se pudo generar el código QR',
      // Chat page
      chatTitle: 'Chat',
      chatPlaceholder: 'Escribe un mensaje…',
      chatReply: 'Responder',
      chatReplyTo: 'Respuesta a',
      chatUser: 'Usuario',
      chatOpenEmoji: 'Abrir emojis',
      chatCloseEmoji: 'Cerrar emojis',
      // My Events page
      eventTitle: 'Mis eventos',
      eventLoading: 'Cargando información del evento...',
      eventEmpty: 'Todavía no hay información disponible para este evento.',
      eventNoEvent: 'No estás inscrito en ningún evento.',
      eventOpenFile: 'Abrir archivo',
      eventTypePin: 'Fijado',
      eventTypeSong: 'Canción',
      eventTypeFile: 'Archivo',
      eventTypePoll: 'Encuesta',
      eventTypeInfo: 'Info',
      // Calendar page
      calTitle: 'Calendario Kingsmen',
      calDate: 'Fecha',
      calTime: 'Hora',
      calClose: 'Cerrar',
      calWeekDays: 'Lun,Mar,Mié,Jue,Vie,Sáb,Dom',
      calMonths: 'Enero,Febrero,Marzo,Abril,Mayo,Junio,Julio,Agosto,Septiembre,Octubre,Noviembre,Diciembre',
    },
  };

  constructor(
    private auth: AuthService,
    private router: Router
  ) {
    addIcons({
      homeOutline,
      personCircleOutline,
      logInOutline,
      logOutOutline,
      qrCodeOutline,
      chatbubblesOutline,
      calendarOutline,
      ribbonOutline,
    });
    void this.initLanguage();
  }

  tr(key: string): string {
    return this.translations[this.selectedLanguage][key] ?? this.translations.en[key] ?? key;
  }

  async setLanguage(code: LanguageCode): Promise<void> {
    this.selectedLanguage = code;
    document.documentElement.lang = code;
    await Preferences.set({ key: 'app_language', value: code });
  }

  private async initLanguage(): Promise<void> {
    const { value } = await Preferences.get({ key: 'app_language' });
    const candidate = (value ?? 'en') as LanguageCode;
    const supported = this.languages.some((lang) => lang.code === candidate);
    this.selectedLanguage = supported ? candidate : 'en';
    document.documentElement.lang = this.selectedLanguage;
  }

  /**
   * Appelé depuis le menu
   */
  async logout(): Promise<void> {
    await this.auth.logout();
    await this.router.navigateByUrl('/login', { replaceUrl: true });
  }
}

type LanguageCode = 'en' | 'nl' | 'fr' | 'de' | 'pl' | 'lt' | 'es';
